name: CI principal
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-run:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        rows: [10, 100, 1000]
        cols: [10, 100, 1000]
        threads: [1, 2, 5]
        method: [0, 1, 2]
        # Excluimos combinaciones que generan demasiadas hebras
        exclude:
        - rows: 100
          cols: 1000
          threads: 2
        - rows: 100
          cols: 1000
          threads: 5
        - rows: 1000
          cols: 100
          threads: 2
        - rows: 1000
          cols: 100
          threads: 5
        - rows: 1000
          cols: 1000
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: make all

      - name: Run
        run: |
          THREADS=$((${{ matrix.rows }} * ${{ matrix.cols }} * ${{ matrix.threads }}))
          ./movies \
              -r ${{ matrix.rows }} \
              -c ${{ matrix.cols }} \
              -t "$THREADS" \
              -m ${{ matrix.method }}

  AddressSanitizer:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        method: [0, 1, 2]
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: make asan
      - name: Run
        run: ./movies -m ${{ matrix.method }}

  ThreadSanitizer:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        method: [0, 1, 2]
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: make tsan
      - name: Run
        run: ./movies -t 1000 -m ${{ matrix.method }}
